import { TestPuzzle } from "@app/test/puzzles/test-puzzle";

export class PuzzleSimple {
  public static readonly PUZZLE_1: TestPuzzle = {
    puzzle: [
      [undefined, 8, undefined, 4, undefined, 9, 6, 5, 3],
      [6, 4, 2, 8, undefined, undefined, undefined, 7, undefined],
      [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        8,
        undefined,
        undefined,
      ],
      [undefined, undefined, 7, undefined, undefined, 5, undefined, 4, 2],
      [
        undefined,
        undefined,
        undefined,
        7,
        undefined,
        1,
        undefined,
        undefined,
        undefined,
      ],
      [8, 5, undefined, 6, undefined, undefined, 1, undefined, undefined],
      [
        undefined,
        undefined,
        6,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      ],
      [undefined, 1, undefined, undefined, undefined, 4, 7, 3, 6],
      [2, 7, 3, 5, undefined, 8, undefined, 1, undefined],
    ],
    solution: [
      [7, 8, 1, 4, 2, 9, 6, 5, 3],
      [6, 4, 2, 8, 5, 3, 9, 7, 1],
      [9, 3, 5, 1, 7, 6, 8, 2, 4],
      [1, 6, 7, 9, 8, 5, 3, 4, 2],
      [3, 2, 9, 7, 4, 1, 5, 6, 8],
      [8, 5, 4, 6, 3, 2, 1, 9, 7],
      [4, 9, 6, 3, 1, 7, 2, 8, 5],
      [5, 1, 8, 2, 9, 4, 7, 3, 6],
      [2, 7, 3, 5, 6, 8, 4, 1, 9],
    ],
  };
  public static readonly PUZZLE_2: TestPuzzle = {
    puzzle: [
      [6, 3, undefined, 2, undefined, 8, undefined, 1, undefined],
      [2, undefined, undefined, undefined, 5, undefined, undefined, 8, 9],
      [1, undefined, 9, undefined, 6, undefined, undefined, 3, undefined],
      [
        undefined,
        undefined,
        8,
        undefined,
        undefined,
        6,
        undefined,
        5,
        undefined,
      ],
      [
        undefined,
        undefined,
        undefined,
        1,
        8,
        7,
        undefined,
        undefined,
        undefined,
      ],
      [
        undefined,
        6,
        undefined,
        5,
        undefined,
        undefined,
        9,
        undefined,
        undefined,
      ],
      [undefined, 9, undefined, undefined, 7, undefined, 1, undefined, 6],
      [8, 1, undefined, undefined, 2, undefined, undefined, undefined, 5],
      [undefined, 2, undefined, 4, undefined, 3, undefined, 9, 7],
    ],
    solution: [
      [6, 3, 5, 2, 9, 8, 7, 1, 4],
      [2, 7, 4, 3, 5, 1, 6, 8, 9],
      [1, 8, 9, 7, 6, 4, 5, 3, 2],
      [7, 4, 8, 9, 3, 6, 2, 5, 1],
      [9, 5, 2, 1, 8, 7, 4, 6, 3],
      [3, 6, 1, 5, 4, 2, 9, 7, 8],
      [4, 9, 3, 8, 7, 5, 1, 2, 6],
      [8, 1, 7, 6, 2, 9, 3, 4, 5],
      [5, 2, 6, 4, 1, 3, 8, 9, 7],
    ],
  };
  public static readonly PUZZLE_3: TestPuzzle = {
    puzzle: [
      [
        undefined,
        undefined,
        undefined,
        1,
        undefined,
        undefined,
        undefined,
        4,
        undefined,
      ],
      [1, 9, 5, undefined, undefined, 8, undefined, undefined, undefined],
      [3, 4, undefined, undefined, 2, undefined, 1, undefined, 9],
      [
        undefined,
        undefined,
        undefined,
        9,
        1,
        undefined,
        5,
        undefined,
        undefined,
      ],
      [6, undefined, 9, 8, undefined, 2, 4, undefined, 7],
      [
        undefined,
        undefined,
        1,
        undefined,
        3,
        4,
        undefined,
        undefined,
        undefined,
      ],
      [2, undefined, 8, undefined, 4, undefined, undefined, 7, 1],
      [undefined, undefined, undefined, 7, undefined, undefined, 8, 3, 2],
      [
        undefined,
        1,
        undefined,
        undefined,
        undefined,
        9,
        undefined,
        undefined,
        undefined,
      ],
    ],
    solution: [
      [8, 2, 6, 1, 9, 3, 7, 4, 5],
      [1, 9, 5, 4, 7, 8, 3, 2, 6],
      [3, 4, 7, 5, 2, 6, 1, 8, 9],
      [4, 8, 2, 9, 1, 7, 5, 6, 3],
      [6, 3, 9, 8, 5, 2, 4, 1, 7],
      [5, 7, 1, 6, 3, 4, 2, 9, 8],
      [2, 6, 8, 3, 4, 5, 9, 7, 1],
      [9, 5, 4, 7, 6, 1, 8, 3, 2],
      [7, 1, 3, 2, 8, 9, 6, 5, 4],
    ],
  };
  public static readonly PUZZLE_4: TestPuzzle = {
    puzzle: [
      [
        undefined,
        undefined,
        7,
        undefined,
        undefined,
        undefined,
        undefined,
        6,
        3,
      ],
      [8, undefined, 4, 6, 7, undefined, 9, undefined, undefined],
      [undefined, 1, undefined, undefined, 3, 9, undefined, undefined, 2],
      [
        undefined,
        undefined,
        3,
        7,
        undefined,
        undefined,
        6,
        undefined,
        undefined,
      ],
      [7, undefined, undefined, 4, undefined, 1, undefined, undefined, 5],
      [
        undefined,
        undefined,
        8,
        undefined,
        undefined,
        6,
        1,
        undefined,
        undefined,
      ],
      [6, undefined, undefined, 2, 1, undefined, undefined, 9, undefined],
      [undefined, undefined, 1, undefined, 6, 3, 5, undefined, 8],
      [
        3,
        9,
        undefined,
        undefined,
        undefined,
        undefined,
        7,
        undefined,
        undefined,
      ],
    ],
    solution: [
      [9, 2, 7, 1, 5, 4, 8, 6, 3],
      [8, 3, 4, 6, 7, 2, 9, 5, 1],
      [5, 1, 6, 8, 3, 9, 4, 7, 2],
      [1, 4, 3, 7, 2, 5, 6, 8, 9],
      [7, 6, 9, 4, 8, 1, 2, 3, 5],
      [2, 5, 8, 3, 9, 6, 1, 4, 7],
      [6, 8, 5, 2, 1, 7, 3, 9, 4],
      [4, 7, 1, 9, 6, 3, 5, 2, 8],
      [3, 9, 2, 5, 4, 8, 7, 1, 6],
    ],
  };
  public static readonly PUZZLE_5: TestPuzzle = {
    puzzle: [
      [9, 8, 1, undefined, undefined, undefined, 7, undefined, undefined],
      [3, undefined, 7, 1, 9, undefined, undefined, 8, undefined],
      [
        undefined,
        undefined,
        4,
        undefined,
        8,
        2,
        undefined,
        undefined,
        undefined,
      ],
      [7, undefined, undefined, 6, undefined, undefined, 3, 9, undefined],
      [
        2,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        7,
      ],
      [undefined, 1, 3, undefined, undefined, 7, undefined, undefined, 5],
      [
        undefined,
        undefined,
        undefined,
        3,
        5,
        undefined,
        2,
        undefined,
        undefined,
      ],
      [undefined, 6, undefined, undefined, 1, 4, 8, undefined, 3],
      [undefined, undefined, 2, undefined, undefined, undefined, 5, 6, 4],
    ],
    solution: [
      [9, 8, 1, 4, 6, 3, 7, 5, 2],
      [3, 2, 7, 1, 9, 5, 4, 8, 6],
      [6, 5, 4, 7, 8, 2, 9, 3, 1],
      [7, 4, 5, 6, 2, 1, 3, 9, 8],
      [2, 9, 6, 5, 3, 8, 1, 4, 7],
      [8, 1, 3, 9, 4, 7, 6, 2, 5],
      [4, 7, 8, 3, 5, 6, 2, 1, 9],
      [5, 6, 9, 2, 1, 4, 8, 7, 3],
      [1, 3, 2, 8, 7, 9, 5, 6, 4],
    ],
  };

  public static readonly PUZZLES: TestPuzzle[] = [
    PuzzleSimple.PUZZLE_1,
    PuzzleSimple.PUZZLE_2,
    PuzzleSimple.PUZZLE_3,
    PuzzleSimple.PUZZLE_4,
    PuzzleSimple.PUZZLE_5,
  ];
}
