import { TestPuzzle } from "@app/test/puzzles/test-puzzle";

export class PuzzleMedium {
  public static readonly PUZZLE_1: TestPuzzle = {
    puzzle: [
      [1, 3, undefined, 8, undefined, undefined, 6, undefined, undefined],
      [
        undefined,
        undefined,
        2,
        undefined,
        undefined,
        7,
        undefined,
        undefined,
        undefined,
      ],
      [undefined, undefined, undefined, 1, 2, undefined, undefined, 7, 9],
      [
        2,
        8,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      ],
      [
        undefined,
        9,
        undefined,
        undefined,
        3,
        undefined,
        undefined,
        1,
        undefined,
      ],
      [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        2,
        3,
      ],
      [5, 7, undefined, undefined, 8, 3, undefined, undefined, undefined],
      [
        undefined,
        undefined,
        undefined,
        4,
        undefined,
        undefined,
        9,
        undefined,
        undefined,
      ],
      [undefined, undefined, 9, undefined, undefined, 2, undefined, 6, 7],
    ],
    solution: [
      [1, 3, 7, 8, 4, 9, 6, 5, 2],
      [9, 5, 2, 3, 6, 7, 1, 8, 4],
      [4, 6, 8, 1, 2, 5, 3, 7, 9],
      [2, 8, 3, 7, 5, 1, 4, 9, 6],
      [6, 9, 5, 2, 3, 4, 7, 1, 8],
      [7, 1, 4, 6, 9, 8, 5, 2, 3],
      [5, 7, 6, 9, 8, 3, 2, 4, 1],
      [8, 2, 1, 4, 7, 6, 9, 3, 5],
      [3, 4, 9, 5, 1, 2, 8, 6, 7],
    ],
  };

  public static readonly PUZZLE_2: TestPuzzle = {
    puzzle: [
      [
        undefined,
        5,
        undefined,
        4,
        undefined,
        undefined,
        undefined,
        7,
        undefined,
      ],
      [
        8,
        undefined,
        undefined,
        undefined,
        undefined,
        5,
        1,
        undefined,
        undefined,
      ],
      [undefined, undefined, 9, 8, 3, undefined, undefined, 5, undefined],
      [
        1,
        undefined,
        8,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      ],
      [2, 4, undefined, undefined, undefined, undefined, undefined, 6, 1],
      [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        3,
        undefined,
        2,
      ],
      [undefined, 1, undefined, undefined, 7, 8, 6, undefined, undefined],
      [
        undefined,
        undefined,
        6,
        3,
        undefined,
        undefined,
        undefined,
        undefined,
        7,
      ],
      [
        undefined,
        9,
        undefined,
        undefined,
        undefined,
        4,
        undefined,
        8,
        undefined,
      ],
    ],
    solution: [
      [3, 5, 1, 4, 6, 2, 9, 7, 8],
      [8, 2, 4, 7, 9, 5, 1, 3, 6],
      [6, 7, 9, 8, 3, 1, 2, 5, 4],
      [1, 3, 8, 2, 4, 6, 7, 9, 5],
      [2, 4, 7, 9, 5, 3, 8, 6, 1],
      [9, 6, 5, 1, 8, 7, 3, 4, 2],
      [4, 1, 3, 5, 7, 8, 6, 2, 9],
      [5, 8, 6, 3, 2, 9, 4, 1, 7],
      [7, 9, 2, 6, 1, 4, 5, 8, 3],
    ],
  };
}
